// `plugin/` is copied into a consumer's own project by `npx skills add
// formio/ai`, so it is shipped product. This suite is an allowlist rather than a
// denylist on purpose: a denylist catches the drift we already found, an
// allowlist forces a decision about anything new.
//
// It asserts on `plugin/` and nothing else. This repository's own ergonomics —
// CLAUDE.md, .claude/, .cursor/, .github/, openspec/ — may favour whichever
// client their maintainers prefer, and are deliberately out of scope.

import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const pluginRoot = join(repoRoot, 'plugin');

// Every entry names who consumes it, so extending this list requires stating an
// audience rather than just making a test pass.
const SHIPPED_ENTRIES: ReadonlyArray<[entry: string, consumer: string]> = [
  ['skills', 'every client — the skill library itself'],
  ['plugin.json', 'Agent Plugins 1.0.0 clients — the vendor-neutral manifest'],
  ['mcp.json', 'Agent Plugins clients — the MCP component'],
  ['.claude-plugin', 'Claude Code — its manifest and install-time userConfig'],
  ['.cursor-plugin', 'Cursor — its manifest and variable declarations'],
  ['package.json', 'npm — publishes the built tree as @formio/ai'],
  ['README.md', 'anyone who installs the bundle'],
  ['CHANGELOG.md', 'anyone upgrading; generated by changesets'],
  ['assets', 'marketplace listings — the logo Cursor requires'],
];

function entriesUnder(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name);
    return entry.isDirectory() ? [full, ...entriesUnder(full)] : [full];
  });
}

describe('the shipped tree is an allowlist', () => {
  it('every top-level entry is declared, with a consumer', () => {
    const allowed = new Set(SHIPPED_ENTRIES.map(([entry]) => entry));
    const present = readdirSync(pluginRoot);
    const undeclared = present.filter((entry) => !allowed.has(entry));

    expect(
      undeclared,
      'a new entry under plugin/ ships to every consumer — declare it in SHIPPED_ENTRIES with who consumes it, or move it out'
    ).toEqual([]);
  });

  it('every declared entry exists', () => {
    const missing = SHIPPED_ENTRIES.map(([entry]) => entry).filter((entry) => {
      try {
        statSync(join(pluginRoot, entry));
        return false;
      } catch {
        return true;
      }
    });

    expect(missing).toEqual([]);
  });
});

describe('no maintainer tooling ships', () => {
  it('no evals directory exists anywhere beneath plugin/', () => {
    const offenders = entriesUnder(pluginRoot)
      .filter((path) => path.split('/').includes('evals'))
      .map((path) => relative(repoRoot, path));

    expect(offenders).toEqual([]);
  });

  it('no grader or benchmark definition ships', () => {
    const offenders = entriesUnder(pluginRoot)
      .filter((path) => /\/(grade\.py|evals\.json)$/.test(path))
      .map((path) => relative(repoRoot, path));

    expect(offenders).toEqual([]);
  });

  it('no Python bytecode ships', () => {
    const offenders = entriesUnder(pluginRoot)
      .filter((path) => path.includes('__pycache__') || path.endsWith('.pyc'))
      .map((path) => relative(repoRoot, path));

    expect(offenders).toEqual([]);
  });
});

describe('the boundary is one-directional', () => {
  // Guards the rule itself: if someone widens this suite to police the
  // repository's own files, that is a scope change and should be a decision
  // rather than a drive-by edit.
  it('asserts on plugin/ only', () => {
    const source = readFileSync(fileURLToPath(import.meta.url), 'utf8');
    const body = source.slice(source.indexOf('describe('));

    for (const ergonomics of ['.claude/', '.cursor/', '.github/', 'openspec/']) {
      expect(body, `${ergonomics} is repository ergonomics, not shipped surface`).not.toContain(
        `join(repoRoot, '${ergonomics}`
      );
    }
  });
});
